{% set version = "1.0.0" %}

package:
  name: future
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/future/future-{{ version }}.tar.gz
  sha256: bd2968309307861edae1458a4f8a4f3598c03be43b97521076aebf5d94c07b05

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv --no-build-isolation

  entry_points:
    - futurize = libfuturize.main:main
    - pasteurize = libpasteurize.main:main

requirements:
  host:
    - python
    - setuptools
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - future
    - libfuturize
    - libpasteurize
    - past
  commands:
    - pip check
    - futurize --help
    - pasteurize --help
  requires:
    - pip

about:
  home: https://python-future.org
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Clean single-source support for Python 3 and 2
  description: |
    Python-future  is the missing compatibility layer between Python 2 and
    Python 3. It allows you to use a single, clean Python 3.x-compatible
    codebase to support both Python 2 and Python 3 with minimal overhead.
  doc_url: https://python-future.org
  dev_url: https://github.com/PythonCharmers/python-future

extra:
  recipe-maintainers:
    - jakirkham
    - mmysinger
    - ocefpaf
